language: python
python:
  - "3.6"

env:
  global:
    secure: <long encrypted string>

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "export DJANGO_KEY=secret"
  - docker-compose run app sh -c "coverage run --source="." manage.py test"

after_script:
- docker-compose run app sh -c "codeclimate-test-reporter --file .coverage"