language: python
python:
  - "3.6"

env:
  global:
    secure: <long encrypted string>

services:
  - docker

before_script: pip install docker-compose

script:
  - export DJANGO_KEY=${DJANGO_KEY}
  - docker-compose run app sh -c "python manage.py test && flake8"