language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "coverage run --source="." manage.py test"
  - docker-compose run app sh -c "coverage report"

after_success:
  - docker-compose run app sh -c "coveralls"