# Generated by Django 2.2.2 on 2019-06-17 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10, 'description is not up to ten characters')]),
        ),
    ]
