# Generated by Django 2.2.2 on 2019-06-17 13:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190617_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, validators=[core.models.validate_min_length]),
        ),
    ]
