# Generated by Django 2.2.2 on 2019-06-17 14:48

import django.contrib.postgres.fields.citext
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190617_1420'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=50, unique=True),
        ),
    ]
