# Generated by Django 2.2.2 on 2019-06-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190617_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'title')},
        ),
    ]
