# Generated by Django 2.2.2 on 2019-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190618_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
