# Generated by Django 2.2.2 on 2019-06-21 11:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190618_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
