# Generated by Django 2.2.2 on 2019-06-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_favorite_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
    ]
