# Generated by Django 2.2.2 on 2019-06-21 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190621_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='ranking',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
