# Generated by Django 2.2.3 on 2019-07-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_historicalcategory_historicalfavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
